// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLPn1shABCSTJbIn5PO5fne-LCT5UsyQ8',
    appId: '1:222206847620:web:0a2ce5677431108e2fb0d1',
    messagingSenderId: '222206847620',
    projectId: 'rara-a10ab',
    authDomain: 'rara-a10ab.firebaseapp.com',
    databaseURL: 'https://rara-a10ab-default-rtdb.firebaseio.com',
    storageBucket: 'rara-a10ab.firebasestorage.app',
    measurementId: 'G-R0X5Z209FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs4c2tgIg7si50Tkdh7q9OFiqLdRn9bMM',
    appId: '1:222206847620:android:91ae397d0e714b3a2fb0d1',
    messagingSenderId: '222206847620',
    projectId: 'rara-a10ab',
    databaseURL: 'https://rara-a10ab-default-rtdb.firebaseio.com',
    storageBucket: 'rara-a10ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvNPEkxzZvPGMkpQfGgvGrXOtDsfUhWn4',
    appId: '1:222206847620:ios:fa4254b53ce1e1c12fb0d1',
    messagingSenderId: '222206847620',
    projectId: 'rara-a10ab',
    databaseURL: 'https://rara-a10ab-default-rtdb.firebaseio.com',
    storageBucket: 'rara-a10ab.firebasestorage.app',
    androidClientId: '222206847620-4nm6vkfc93avhnao75lf91hl68jqteb1.apps.googleusercontent.com',
    iosClientId: '222206847620-518u0dun5jobsk5tjp7f1jrl381repkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.visionar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvNPEkxzZvPGMkpQfGgvGrXOtDsfUhWn4',
    appId: '1:222206847620:ios:fa4254b53ce1e1c12fb0d1',
    messagingSenderId: '222206847620',
    projectId: 'rara-a10ab',
    databaseURL: 'https://rara-a10ab-default-rtdb.firebaseio.com',
    storageBucket: 'rara-a10ab.firebasestorage.app',
    androidClientId: '222206847620-4nm6vkfc93avhnao75lf91hl68jqteb1.apps.googleusercontent.com',
    iosClientId: '222206847620-518u0dun5jobsk5tjp7f1jrl381repkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.visionar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLPn1shABCSTJbIn5PO5fne-LCT5UsyQ8',
    appId: '1:222206847620:web:69a42439cf04ee732fb0d1',
    messagingSenderId: '222206847620',
    projectId: 'rara-a10ab',
    authDomain: 'rara-a10ab.firebaseapp.com',
    databaseURL: 'https://rara-a10ab-default-rtdb.firebaseio.com',
    storageBucket: 'rara-a10ab.firebasestorage.app',
    measurementId: 'G-9R0GXQR88J',
  );
}
